"""Estilo de casa y figuras.

La implementación vive en ``regimenes.viz.figuras``; aquí se re-exporta su API
pública y los tres dicts de ventanas de ``regimenes.evaluacion.metricas`` (mismos
objetos), de modo que ``from regimenes import viz; viz.CRISIS_WINDOWS`` funcione.
"""

from regimenes.viz.figuras import (
    SHORT,
    _K_SUFFIX,
    C_LONG,
    C_SHORT,
    C_NEG,
    C_NA,
    C_CRISIS,
    C_FP,
    REGIME_COLORS,
    HOUSE_RC,
    canonical_detector,
    detector_short,
    use_house_style,
    regime_color,
    shade_regime,
    episode_durations,
    plot_price_by_regime,
    plot_regime_timeline,
    plot_crisis_probability,
    plot_duration_histogram,
    plot_transition_matrix,
    plot_metric_comparison,
    plot_distribution_by_regime,
    plot_feature_space_scatter,
    plot_regime_correlation_heatmaps,
    plot_fold_panel,
    render_table_figure,
    plot_grouped_bars,
    CRISIS_WINDOWS,
    FALSE_POSITIVE_WINDOWS,
    DRAWDOWN_TROUGHS,
)

__all__ = [
    "SHORT",
    "_K_SUFFIX",
    "C_LONG",
    "C_SHORT",
    "C_NEG",
    "C_NA",
    "C_CRISIS",
    "C_FP",
    "REGIME_COLORS",
    "HOUSE_RC",
    "canonical_detector",
    "detector_short",
    "use_house_style",
    "regime_color",
    "shade_regime",
    "episode_durations",
    "plot_price_by_regime",
    "plot_regime_timeline",
    "plot_crisis_probability",
    "plot_duration_histogram",
    "plot_transition_matrix",
    "plot_metric_comparison",
    "plot_distribution_by_regime",
    "plot_feature_space_scatter",
    "plot_regime_correlation_heatmaps",
    "plot_fold_panel",
    "render_table_figure",
    "plot_grouped_bars",
    "CRISIS_WINDOWS",
    "FALSE_POSITIVE_WINDOWS",
    "DRAWDOWN_TROUGHS",
]
