"""Construye y EJECUTA notebooks/04_hmm_gaussian_2s.ipynb (D4).

Reproduccion FIEL (celda por celda) del notebook D4: HMM gaussiano 2 estados,
baseline-puente que compara la version IN-SAMPLE (no causal, Viterbi sobre toda
la muestra) contra la version CAUSAL walk-forward (filtrado forward). Mismo patron
que _build_02.py: nbformat para montar las celdas + ExecutePreprocessor (kernel
python3). D4 es COSTOSO (~15-20 min walk-forward) -> timeout generoso. Tras
ejecutar comprueba 0 errores leyendo los outputs. Figuras y CSV -> results/.
NO escribe metrics_master.csv (Ola 0); solo sus metrics_04_*.csv y figuras.
"""
from pathlib import Path

import nbformat as nbf
from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook
from nbconvert.preprocessors import ExecutePreprocessor

ROOT = Path(__file__).resolve().parents[2]
NB_PATH = ROOT / "notebooks" / "04_hmm_gaussian_2s.ipynb"

cells = []

cells.append(new_markdown_cell('# 04 — D4 `hmm_gaussian_2s`: HMM gaussiano 2 estados (BASELINE-PUENTE)\n\n**Familia F3 (HMM).** Un *Hidden Markov Model* (HMM) añade a la mezcla gaussiana lo que al GMM de D3 le faltaba: una **cadena de Markov** sobre el estado latente. El régimen de hoy ya no se decide de forma aislada, sino condicionado al de ayer a través de una **matriz de transición** cuya diagonal alta premia la persistencia. Por eso D4 es el complemento natural de D3: mismas features (aquí un subconjunto puente de 7), misma evaluación, y la única diferencia conceptual es la dinámica temporal.\n\n**Razón de ser de D4: es el puente con la tarea previa y MIDE el efecto del look-ahead.** Reproduce honestamente el detector de la práctica anterior (`GaussianHMM`, `covariance_type=\'full\'`, 2 estados) y lo somete a un experimento controlado: comparar dos versiones del MISMO modelo.\n1. **IN-SAMPLE (NO causal).** Ajuste y decodificación de Viterbi sobre TODA la muestra. *Look-ahead* significa "ver el futuro": el algoritmo EM estima los parámetros con todo el histórico y el Viterbi suaviza la secuencia de estados mirando días posteriores. Reproduce la tarea previa, pero por eso NO es comparable con detectores causales; se reporta aparte y claramente etiquetada.\n2. **CAUSAL walk-forward.** Cada fold reentrena solo con el pasado y decodifica el bloque siguiente con **filtrado forward** (solo observaciones ≤ t). Es la versión comparable con el resto del banco.\n\nLa distancia entre ambas mide exactamente **cuánto del acierto de la tarea previa dependía de ver el futuro**.\n\n**Hipótesis del CHECKPOINT 2 para D4:** *captará 2008 y 2020 (crisis grandes y persistentes); fallará 2013 y 2018 (correcciones rápidas, donde el supuesto gaussiano subestima las colas); la versión in-sample es NO causal.*\n\nMemoria: `docs/memory/detectors/04_hmm_gaussian_2s.md`.'))

cells.append(new_markdown_cell('### Índice navegable\n\n0. *(arriba)* Presentación: por qué D4 es el baseline-puente y qué mide el experimento central.\n1. [Features puente (las 7 de la tarea previa)](#1.-Features-puente) — qué entra al modelo y por qué es causal.\n2. [Versión IN-SAMPLE (⚠️ no causal)](#2.-Versión-IN-SAMPLE) — Viterbi global, reproduce la tarea previa.\n3. [Versión CAUSAL walk-forward](#3.-Versión-CAUSAL-walk-forward) — filtrado forward, la comparable.\n4. [Comparación in-sample vs causal: ¿cuánto era look-ahead?](#4.-Comparación-IN-SAMPLE-vs-CAUSAL) — **tabla limpia** + barras de cobertura.\n5. [S&P 500 coloreado por régimen](#5.-S&P-500-coloreado-por-régimen) — lectura visual de ambas versiones.\n6. [Probabilidad de crisis y verificación](#6.-Probabilidad-de-crisis) — señal blanda y lead/lag.\n7. [Filtrado vs suavizado: el corazón causal de D4](#7.-Filtrado-vs-suavizado) — dónde nace el look-ahead intra-bloque.\n8. [Emisiones por estado y matriz de transición](#8.-Emisiones-por-estado) — qué \"ve\" cada gaussiana y la persistencia.\n9. [Matriz de transición y timeline](#9.-Matriz-de-transición-y-timeline) — duración esperada de regímenes.\n10. [Volcado de métricas a results/](#10.-Volcado-de-métricas) — los dos CSV (causal e in-sample).\n11. [Conclusión: veredicto sobre la hipótesis CP2](#11.-Conclusión) — qué era reproducible y qué era fuga de futuro.\n\n> **Hilo conductor de D4.** Todo el notebook gira en torno a una sola distinción: **filtrado** (probabilidad de hoy usando solo el pasado, P(estado_t | obs ≤ t), *causal*) frente a **suavizado** (probabilidad de hoy reescrita a la luz del futuro, P(estado_t | toda la muestra), *con look-ahead*). La tarea previa vivía en el segundo mundo; el banco de pruebas exige el primero. La **distancia entre ambos** es, literalmente, la cantidad de acierto que dependía de ver el futuro.'))

cells.append(new_code_cell("%matplotlib inline\nimport sys, warnings\nfrom pathlib import Path\nimport numpy as np, pandas as pd\nimport matplotlib.pyplot as plt\nimport matplotlib.patches as mpatches\nimport seaborn as sns\nwarnings.filterwarnings('ignore')\nROOT = Path.cwd()\nwhile not (ROOT / 'src').exists() and ROOT != ROOT.parent:\n    ROOT = ROOT.parent\nsys.path.insert(0, str(ROOT))\nRESULTS = ROOT / 'results'; RESULTS.mkdir(exist_ok=True)\nsns.set_theme(style='whitegrid', context='notebook')\nfrom src import evaluation as ev\nfrom src import viz                 # helpers canonicos de figuras (estilo de casa)\nviz.use_house_style()               # rcParams homogeneos con el resto del banco\nfrom detectors.hmm_gaussian_2s import HMMGaussian2S, BRIDGE_FEATURES\n\nfeats = pd.read_parquet(ROOT / 'data' / 'processed' / 'features.parquet')\nraw = pd.read_parquet(ROOT / 'data' / 'raw' / 'raw_panel.parquet')\nX = feats[BRIDGE_FEATURES].copy()\n# market_returns = retorno log S&P 500 reindexado a la ventana de features\nmkt = np.log(raw['SP500'] / raw['SP500'].shift(1)).reindex(X.index)\nspx = raw['SP500'].reindex(X.index)\nprint('Features puente (7):', BRIDGE_FEATURES)\nprint('Ventana:', X.index.min().date(), '->', X.index.max().date(), '| n =', len(X))"))

cells.append(new_markdown_cell('## 1. Features puente\n\nPara que el puente con la tarea previa sea legítimo, D4 usa exactamente sus mismas entradas: un subconjunto de **7** de las 15 features causales de `features.parquet` —retornos z de SP500/TLT/IEF/HYG, volatilidad realizada z, spread de crédito HYG−IEF z y **nivel** de VIX z—. Todas son causales por construcción, porque sus z-scores se estandarizan con media y desviación **expanding** (en t solo usan datos ≤ t), evitando la fuga de futuro que supondría normalizar con estadísticos de toda la muestra.'))

cells.append(new_code_cell("X.describe().T[['mean','std','min','max']].round(3)"))

cells.append(new_markdown_cell('## 2. Versión IN-SAMPLE (⚠️ NO CAUSAL — con look-ahead)\n\nAjuste del HMM y decodificación de **Viterbi** —el algoritmo que reconstruye la secuencia de estados más probable— sobre **toda** la muestra (2007+). Reproduce la tarea previa. **Tiene look-ahead** por una vía sutil: aunque los z-scores de entrada ya son causales, el EM estima los parámetros viendo todo el histórico y el Viterbi suaviza cada día usando también observaciones futuras. Se reporta SOLO como referencia, claramente etiquetada como NO causal; NO es comparable con los detectores del banco.'))

cells.append(new_code_cell("det_is = HMMGaussian2S(n_states=2, n_init=5).fit(X)\ndet_is.label_states_economically(X, market_returns=mkt)  # orden económico con S&P 500\nstates_is = pd.Series(det_is.predict(X), index=X.index, name='state')\np_is = pd.Series(det_is.crisis_probability(X), index=X.index, name='p_crisis')\nprint('crisis_state =', det_is.crisis_state, '| logL =', round(det_is.score(X), 1),\n      '| n_params =', det_is.n_parameters())\n# Retorno medio anualizado por estado (validación económica)\nfor s in sorted(states_is.unique()):\n    r = mkt[states_is == s]\n    print(f'  estado {s}: ret medio anual = {r.mean()*252:+.2%} | vol anual = {r.std()*np.sqrt(252):.2%} | dias = {len(r)}')"))

cells.append(new_code_cell("# Cobertura de crisis y falsas alarmas en ventanas trampa (IN-SAMPLE)\ncov_is = ev.crisis_coverage(states_is, det_is.crisis_state)\nfa_is = ev.false_alarm_in_windows(states_is, det_is.crisis_state)\nprint('Cobertura de crisis (IN-SAMPLE):')\nfor k, v in cov_is.items(): print(f'  {k:16s}: {v:6.1%}')\nprint('Falsas alarmas en ventanas trampa (IN-SAMPLE):')\nfor k, v in fa_is.items(): print(f'  {k:16s}: {v:6.1%}')"))

cells.append(new_code_cell("# Construir un 'panel' in-sample para reutilizar ev.evaluate (fila comparable, NO causal)\npanel_is = pd.DataFrame({'state': states_is, 'p_crisis': p_is, 'fold': 0})\nres_is = ev.evaluate(det_is, panel_is, market_returns=mkt, X_full=X)\nres_is.detector_name = 'hmm_gaussian_2s_INSAMPLE_noncausal'\nprint('switching_rate =', round(res_is.switching_rate, 4),\n      '| dur media =', round(res_is.mean_regime_duration, 1), 'dias',\n      '| AIC =', round(res_is.aic, 1), '| BIC =', round(res_is.bic, 1))"))

cells.append(new_markdown_cell('## 3. Versión CAUSAL walk-forward (la comparable)\n\n`ev.walk_forward` reentrena el HMM en ventanas **expanding** y predice el siguiente bloque de `step=21` días usando SOLO el pasado. Cada fold fija sus parámetros y su orden económico con su propio train.\n\n**Nota de causalidad (estricta).** La etiqueta y la probabilidad de cada día las produce un **filtrado forward** (`predict_online`/`predict_proba` sobrescritos): la creencia de estado se propaga hacia delante usando solo observaciones ≤ t, sin el suavizado *forward-backward* ni el Viterbi de `hmmlearn`, que mirarían días futuros del propio bloque. Es la diferencia entre la probabilidad **filtrada** P(estado_t | obs ≤ t) —causal— y la **suavizada** P(estado_t | toda la muestra) —con look-ahead—. Así no entra ni un día de futuro intra-bloque; el Viterbi global queda confinado a la versión in-sample de arriba.\n\n**Tensión de cobertura (FASE 1):** la GFC 2008 está pegada al inicio de los datos (2007-04). Con un train inicial de varios años, **2008 y 2011 caen DENTRO del train** → no son OOS → su cobertura sale **NaN**. Es correcto, y es justo el punto metodológico a documentar: con features que arrancan en 2007 no se puede evaluar 2008 de forma causal sin sacrificar casi todo el train.'))

cells.append(new_code_cell("TRAIN_SIZE = 252 * 5   # ~5 anios de train inicial (2008 y 2011 quedan en train)\nSTEP = 21              # reentrena cada ~mes; filtrado forward intra-bloque (causal, no Viterbi)\npanel = ev.walk_forward(lambda: HMMGaussian2S(n_states=2, n_init=5),\n                        X, train_size=TRAIN_SIZE, step=STEP, expanding=True)\nprint('OOS:', panel.index.min().date(), '->', panel.index.max().date(), '| n_oos =', len(panel))\nstates_c = panel['state']; p_c = panel['p_crisis']\npanel.head(3)"))

cells.append(new_code_cell("# Detector ajustado a TODA la muestra solo para logL/AIC/BIC (la clasificacion es la del panel OOS)\ndet_c = HMMGaussian2S(n_states=2, n_init=5).fit(X)\ndet_c.label_states_economically(X, market_returns=mkt)\nres_c = ev.evaluate(det_c, panel, market_returns=mkt, X_full=X)\nprint('ventana_eval:', res_c.extra['ventana_eval'])\nprint('Cobertura de crisis (CAUSAL OOS):')\nfor k, v in res_c.crisis_coverage.items():\n    print(f'  {k:16s}: ' + ('NaN (en train, no OOS)' if v != v else f'{v:6.1%}'))\nprint('Falsas alarmas en ventanas trampa (CAUSAL OOS):')\nfor k, v in res_c.false_alarm_in_fp.items():\n    print(f'  {k:16s}: ' + ('NaN' if v != v else f'{v:6.1%}'))\nprint(f'switching_rate = {res_c.switching_rate:.4f} | dur media = {res_c.mean_regime_duration:.1f} dias'\n      f' | label_stability = {res_c.label_stability:.3f}')"))

cells.append(new_markdown_cell('## 4. Comparación IN-SAMPLE vs CAUSAL: ¿cuánto era look-ahead?\n\nEste es el **experimento central de D4**. Misma arquitectura, misma ventana de datos, mismas 7 features: lo único que cambia es si el modelo puede o no asomarse al futuro. La **diferencia de cobertura por ventana** mide, casilla a casilla, cuánto del acierto de la tarea previa dependía de ese privilegio.\n\nCómo leer la tabla y las barras:\n\n- **`NaN` en la columna causal** → la crisis cayó en el train inicial (2008, 2011 con ~5 años de burn-in): no es evaluable OOS. *No es que el modelo empeore*; es que, honestamente, no podemos puntuarla sin sacrificar casi todo el train. Documentarlo es parte del valor de D4.\n- **`delta = causal − in-sample`** → donde ambas versiones dan número, su distancia es el efecto neto del look-ahead. Un `delta` muy negativo en una crisis significaría que el acierto previo era, en buena parte, fuga de futuro; un `delta` cercano a cero significa que la detección sobrevive a la causalidad.\n- **Ventanas trampa (2013/2018)** → aquí el número es **falsa alarma**, no cobertura: cuanto más bajo, mejor.\n\nPrimero la tabla limpia (figura embebible, sin el `Styler` crudo de pandas); después dos lecturas en barras del mismo contenido.'))

cells.append(new_code_cell("rows = []\nfor k in ev.CRISIS_WINDOWS:\n    rows.append({'ventana': k, 'tipo': 'crisis',\n                 'IN_SAMPLE': cov_is.get(k, float('nan')),\n                 'CAUSAL_OOS': res_c.crisis_coverage.get(k, float('nan'))})\nfor k in ev.FALSE_POSITIVE_WINDOWS:\n    rows.append({'ventana': k, 'tipo': 'trampa (FP)',\n                 'IN_SAMPLE': fa_is.get(k, float('nan')),\n                 'CAUSAL_OOS': res_c.false_alarm_in_fp.get(k, float('nan'))})\ncmp = pd.DataFrame(rows).set_index('ventana')\ncmp['delta'] = cmp['CAUSAL_OOS'] - cmp['IN_SAMPLE']\n# FIX: en lugar de devolver un Styler crudo de pandas (que en texto plano sale como\n# '<pandas...Styler at 0x...>'), renderizamos una TABLA LIMPIA como figura embebible\n# (viz.render_table_figure) y la guardamos. 'delta' = CAUSAL - IN_SAMPLE: negativo en\n# crisis => la version causal cubre MENOS (parte del acierto previo era look-ahead);\n# NaN => la ventana cayo en el train inicial y no es evaluable OOS.\nfig_tbl = viz.render_table_figure(\n    cmp, title='D4 - cobertura por ventana: IN-SAMPLE vs CAUSAL  (delta = causal - in-sample)',\n    highlight_cols=['delta'],\n    fmt={'IN_SAMPLE': '{:.1%}', 'CAUSAL_OOS': '{:.1%}', 'delta': '{:+.1%}'})\nfig_tbl.savefig(RESULTS / 'd4_insample_vs_causal_table.png', dpi=150, bbox_inches='tight')\nplt.show()\n# Y dejamos tambien un display tabular limpio (no un Styler) como respaldo en texto.\ncmp.round(3)"))

cells.append(new_code_cell("fig, ax = plt.subplots(figsize=(11, 4.5))\nplotdf = cmp[['IN_SAMPLE', 'CAUSAL_OOS']]\nplotdf.plot(kind='bar', ax=ax, color=['#c0392b', '#2980b9'], width=0.8)\nax.set_ylabel('% dias en estado crisis'); ax.axhline(0.5, color='grey', ls='--', lw=0.8)\nax.set_title('Cobertura por ventana: IN-SAMPLE (no causal) vs CAUSAL OOS\\n(barras ausentes en CAUSAL = ventana en train inicial, no OOS)')\nax.set_xticklabels([t.get_text() for t in ax.get_xticklabels()], rotation=30, ha='right')\nfig.tight_layout(); fig.savefig(RESULTS / 'metrics_04_coverage_compare.png', dpi=110, bbox_inches='tight')\nplt.show()"))

cells.append(new_code_cell("# Lectura 'de casa' del MISMO contraste, centrada en la COBERTURA DE CRISIS (donde se\n# juega el look-ahead). Barras agrupadas con la paleta canonica: rojo = in-sample\n# (no causal), azul = causal OOS. Donde el causal no tiene barra, la ventana estaba en\n# el train inicial (NaN, no evaluable OOS).\ncats = list(ev.CRISIS_WINDOWS.keys())\nseries = {\n    'in-sample (no causal)': [cov_is.get(k, float('nan')) for k in cats],\n    'causal OOS': [res_c.crisis_coverage.get(k, float('nan')) for k in cats],\n}\nax = viz.plot_grouped_bars(cats, series, ylabel='cobertura (fraccion de dias en crisis)',\n                           title='D4 - cobertura de crisis por ventana: el efecto del look-ahead',\n                           colors=[viz.C_CRISIS, viz.C_LONG], rotation=20, value_labels=True)\nax.axhline(0.5, color='grey', ls='--', lw=0.8)\nax.figure.savefig(RESULTS / 'd4_coverage_bars.png', dpi=150, bbox_inches='tight')\nplt.show()"))

cells.append(new_markdown_cell('## 5. S&P 500 coloreado por régimen (in-sample vs causal)\n\nMisma lectura visual en las dos versiones, una sobre otra. El sombreado rojo marca los días clasificados como **crisis**; las líneas verticales señalan las ventanas de crisis conocidas. Arriba la versión in-sample (toda la muestra); abajo la causal (solo el tramo OOS). El contraste deja ver de un vistazo dónde el suavizado in-sample "limpia" el recorrido que el filtrado causal entrega más fragmentado.'))

cells.append(new_code_cell("def shade_regime(ax, states, crisis_state, color='red', alpha=0.25):\n    is_cr = (states == crisis_state).astype(int).values\n    idx = states.index\n    start = None\n    for i in range(len(is_cr)):\n        if is_cr[i] and start is None:\n            start = idx[i]\n        if (not is_cr[i] or i == len(is_cr)-1) and start is not None:\n            end = idx[i]\n            ax.axvspan(start, end, color=color, alpha=alpha, lw=0)\n            start = None\n\nfig, axes = plt.subplots(2, 1, figsize=(15, 8), sharex=True)\nfor ax, st, ttl in [(axes[0], states_is, 'IN-SAMPLE (NO causal)'),\n                    (axes[1], states_c, 'CAUSAL walk-forward (OOS)')]:\n    ax.plot(spx.index, spx, color='black', lw=0.7)\n    ax.set_yscale('log'); ax.set_ylabel('S&P 500 (log)')\n    shade_regime(ax, st, det_is.crisis_state)\n    for a, b in ev.CRISIS_WINDOWS.values():\n        ax.axvline(pd.Timestamp(a), color='blue', ls=':', lw=0.7)\n    ax.set_title(f'S&P 500 — regimen CRISIS sombreado | {ttl}')\nfig.tight_layout(); fig.savefig(RESULTS / 'metrics_04_price_by_regime.png', dpi=110, bbox_inches='tight')\nplt.show()"))

cells.append(new_markdown_cell('## 6. Probabilidad de crisis y verificación contra eventos\n\nLa probabilidad blanda `P(crisis)` (posteriores del HMM) matiza la decisión dura y permite leer cobertura y **lead/lag** —cuántos días se adelanta o retrasa la señal respecto al suelo del drawdown—. Superponemos las ventanas de crisis (rojo) y de trampa (naranja), y comparamos la curva in-sample (toda la muestra) con la causal (OOS). Conviene recordar que el lead/lag está **censurado por la ventana de búsqueda**: solo se mide dentro de un margen acotado, así que sus magnitudes son orientativas, no exactas.'))

cells.append(new_code_cell("fig, ax = plt.subplots(figsize=(15, 4.5))\nax.plot(p_is.index, p_is, color='#c0392b', lw=0.7, alpha=0.8, label='P(crisis) IN-SAMPLE')\nax.plot(p_c.index, p_c, color='#2980b9', lw=0.9, label='P(crisis) CAUSAL OOS')\nax.axhline(0.5, color='grey', ls='--', lw=0.8)\nfor a, b in ev.CRISIS_WINDOWS.values(): ax.axvspan(pd.Timestamp(a), pd.Timestamp(b), color='red', alpha=0.12)\nfor a, b in ev.FALSE_POSITIVE_WINDOWS.values(): ax.axvspan(pd.Timestamp(a), pd.Timestamp(b), color='orange', alpha=0.18)\nax.set_ylabel('P(crisis)'); ax.set_ylim(-0.02, 1.02); ax.legend(loc='upper left', fontsize=9)\nax.set_title('Probabilidad de crisis: crisis (rojo) vs trampas 2013/2018 (naranja)')\nfig.tight_layout(); fig.savefig(RESULTS / 'metrics_04_crisis_proba.png', dpi=110, bbox_inches='tight')\nplt.show()"))

cells.append(new_markdown_cell('## 7. Filtrado vs suavizado — el corazón causal de D4\n\nLa distinción que vertebra todo el notebook merece verse de forma aislada y controlada. Aquí fijamos **los mismos parámetros** (el HMM ajustado in-sample sobre toda la muestra) y comparamos las dos formas de leer la probabilidad de crisis de cada día:\n\n- **Suavizado (forward-backward, rojo):** P(estado_t | *toda* la muestra). Es lo que `hmmlearn` devuelve por defecto y lo que usaba la tarea previa. Reescribe la creencia de hoy con observaciones **futuras** → tiene look-ahead.\n- **Filtrado forward (azul):** P(estado_t | obs ≤ t). Solo el pasado. Es la lectura causal que el banco exige y la que alimenta la versión walk-forward.\n\nAl compartir parámetros, la **única** diferencia entre las dos curvas es el flujo de información temporal: la brecha entre ellas es, en estado puro, el look-ahead *intra-bloque* que la versión causal renuncia a usar. Donde el suavizado «sabe» antes que una racha de turbulencia va a consolidarse y sube limpiamente, el filtrado titubea hasta tener evidencia acumulada — exactamente el coste honesto de no mirar el futuro.'))

cells.append(new_code_cell("# Suavizado (forward-backward de hmmlearn) vs filtrado forward (causal), MISMOS\n# parametros in-sample. Reordenamos la columna de crisis al orden economico canonico.\nXsel = X[BRIDGE_FEATURES].values\nsm = det_is._model.predict_proba(Xsel)            # suavizado, orden INTERNO de hmmlearn\nci = int(det_is._canonical_order[det_is.crisis_state])  # columna interna = estado crisis\np_smooth = pd.Series(sm[:, ci], index=X.index, name='p_smooth')\np_filt = p_is                                     # ya es el FILTRADO causal (predict_proba)\nfig, ax = plt.subplots(figsize=(15, 4.5))\nax.plot(p_smooth.index, p_smooth, color=viz.C_CRISIS, lw=0.9,\n        label='SUAVIZADO forward-backward (NO causal: usa el futuro del bloque)')\nax.plot(p_filt.index, p_filt, color=viz.C_LONG, lw=0.9, alpha=0.85,\n        label='FILTRADO forward (causal: solo obs <= t)')\nax.axhline(0.5, color='grey', ls='--', lw=0.8)\nfor a, b in ev.CRISIS_WINDOWS.values():\n    ax.axvspan(pd.Timestamp(a), pd.Timestamp(b), color='red', alpha=0.10)\nax.set_ylim(-0.02, 1.02); ax.set_ylabel('P(crisis)')\nax.legend(loc='upper left', fontsize=9)\nax.set_title('Filtrado vs suavizado (mismos parametros in-sample): la brecha ES el look-ahead intra-bloque')\nfig.tight_layout(); fig.savefig(RESULTS / 'd4_filter_vs_smooth.png', dpi=150, bbox_inches='tight')\nplt.show()\ngap = (p_smooth - p_filt).abs()\nprint(f'Brecha |suavizado - filtrado|: media = {gap.mean():.3f} | p95 = {gap.quantile(0.95):.3f} | max = {gap.max():.3f}')\nprint('(brecha grande => el suavizado se apoyaba mucho en el futuro para fijar la etiqueta de ese dia)')"))

cells.append(new_markdown_cell('## 8. Emisiones gaussianas por estado y matriz de transición (estilo de casa)\n\nAntes de mirar la dinámica conviene ver de qué están hechas las **emisiones**: qué soporte tiene cada feature dentro de cada estado. Si las gaussianas de calma y crisis se solapan poco en las variables clave (nivel de VIX, retorno del S&P 500), el modelo tiene una señal limpia que separar; si se solapan mucho, la decisión es frágil. A la derecha, la **matriz de transición A** —misma información que la sección 9 pero con el helper canónico del banco— resume la persistencia: la diagonal alta es lo que convierte un GMM sin memoria en un HMM con inercia de régimen.'))

cells.append(new_code_cell("# Emisiones por estado (violines) + matriz de transicion, todo con la paleta de casa.\norder = det_is._canonical_order\nP = det_is._model.transmat_[np.ix_(order, order)]   # A en orden economico 0=calma,1=crisis\nlbl = {0: 'calma', 1: 'crisis'}\nfig, axes = plt.subplots(1, 3, figsize=(16, 4.4))\nviz.plot_distribution_by_regime(X['VIX_level_z'], states_is, crisis_state=det_is.crisis_state,\n                                labels=lbl, kind='violin', ax=axes[0],\n                                xlabel='VIX_level_z', title='Nivel de VIX (z) por estado')\nviz.plot_distribution_by_regime(X['SP500_ret_z'], states_is, crisis_state=det_is.crisis_state,\n                                labels=lbl, kind='violin', ax=axes[1],\n                                xlabel='SP500_ret_z', title='Retorno S&P 500 (z) por estado')\nviz.plot_transition_matrix(P, labels=['calma', 'crisis'], ax=axes[2],\n                           title='Matriz de transicion A (orden economico)')\nfig.suptitle('D4 - emisiones por estado (in-sample) y dinamica de transicion', y=1.03)\nfig.tight_layout(); fig.savefig(RESULTS / 'd4_dist_by_state.png', dpi=150, bbox_inches='tight')\nplt.show()"))

cells.append(new_markdown_cell('## 9. Matriz de transición y timeline\n\nAquí se hace visible lo que distingue a un HMM de un GMM. La **matriz de transición A** (ajuste in-sample, reordenada al orden económico 0=calma · 1=crisis) recoge la probabilidad de pasar de un régimen a otro de un día para el siguiente; su **diagonal alta** es el término de persistencia que el GMM no tenía, y de ella se deriva la duración esperada de cada régimen (1/(1−A_ii)). A la derecha, el timeline de regímenes OOS muestra cómo esa persistencia se traduce en bloques más largos que el parpadeo de D3.'))

cells.append(new_code_cell("order = det_is._canonical_order\nP = det_is._model.transmat_[np.ix_(order, order)]\ndur_calm = 1.0 / (1.0 - P[0, 0]); dur_cri = 1.0 / (1.0 - P[1, 1])\nfig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4), gridspec_kw={'width_ratios': [1, 2.4]})\nsns.heatmap(P, annot=True, fmt='.3f', cmap='viridis', cbar=False,\n            xticklabels=['calma', 'crisis'], yticklabels=['calma', 'crisis'], ax=ax1)\nax1.set_title(f'Matriz de transicion A\\n(dur. esperada: calma {dur_calm:.0f}d, crisis {dur_cri:.0f}d)')\nax1.set_xlabel('a estado'); ax1.set_ylabel('desde estado')\ntl = (states_c == det_is.crisis_state).astype(int).values.reshape(1, -1)\nax2.imshow(tl, aspect='auto', cmap='Reds', extent=[0, len(states_c), 0, 1])\nax2.set_yticks([]); ax2.set_title('Timeline regimen CAUSAL OOS (rojo=crisis)')\ntick = np.linspace(0, len(states_c)-1, 6).astype(int)\nax2.set_xticks(tick); ax2.set_xticklabels([states_c.index[t].year for t in tick])\nfig.tight_layout(); fig.savefig(RESULTS / 'metrics_04_transition_timeline.png', dpi=110, bbox_inches='tight')\nplt.show()"))

cells.append(new_code_cell("# Histograma de duraciones de episodios (detecta flickering) — version causal OOS\ndef episode_durations(states):\n    v = states.values; out = {0: [], 1: []}\n    run = 1\n    for i in range(1, len(v)):\n        if v[i] == v[i-1]: run += 1\n        else: out[int(v[i-1])].append(run); run = 1\n    out[int(v[-1])].append(run); return out\ndur = episode_durations(states_c)\nfig, ax = plt.subplots(figsize=(10, 4))\nax.hist(dur[0], bins=30, alpha=0.6, label=f'calma (n={len(dur[0])})', color='#2980b9')\nax.hist(dur[1], bins=30, alpha=0.6, label=f'crisis (n={len(dur[1])})', color='#c0392b')\nax.set_xlabel('duracion del episodio (dias)'); ax.set_ylabel('frecuencia'); ax.legend()\nax.set_title('Duracion de episodios (CAUSAL OOS) — colas cortas = flickering')\nfig.tight_layout(); fig.savefig(RESULTS / 'metrics_04_durations.png', dpi=110, bbox_inches='tight')\nplt.show()"))

cells.append(new_markdown_cell('## 10. Volcado de métricas a `results/`\n\nSe guardan dos filas, deliberadamente separadas para no mezclar lo comparable con lo que no lo es:\n\n- `metrics_04_hmm_gaussian_2s.csv` → versión **CAUSAL** (la que entra en la comparativa del banco).\n- `metrics_04_hmm_gaussian_2s_insample.csv` → versión in-sample (NO causal), solo como referencia del puente con la tarea previa.'))

cells.append(new_code_cell("tbl_c = ev.results_table([res_c])\ntbl_c.to_csv(RESULTS / 'metrics_04_hmm_gaussian_2s.csv', index=False)\ntbl_is = ev.results_table([res_is])\ntbl_is.to_csv(RESULTS / 'metrics_04_hmm_gaussian_2s_insample.csv', index=False)\nprint('Guardados:')\nprint('  results/metrics_04_hmm_gaussian_2s.csv          (CAUSAL, comparable)')\nprint('  results/metrics_04_hmm_gaussian_2s_insample.csv (IN-SAMPLE, no causal)')\ntbl_c.T"))

cells.append(new_markdown_cell('## 11. Conclusión D4 — veredicto sobre la hipótesis del CHECKPOINT 2\n\n**Hipótesis CP2:** *capta 2008 y 2020; falla 2013 y 2018; la versión in-sample es NO causal.* Los números de arriba son **consistentes con** la hipótesis (no la "confirman" en sentido estadístico: son n≈4 crisis sin contraste de significancia):\n\n- **2008/2020 in-sample:** cobertura muy alta —reproduce fielmente la tarea previa— ✓.\n- **2013/2018:** baja cobertura sostenida ✓. El supuesto gaussiano subestima las colas (kurtosis 25–40 en el EDA) y prioriza los episodios largos de alta varianza, perdiéndose las correcciones rápidas. Es justo la motivación de los detectores posteriores con colas pesadas (HMM t-Student) y más estados.\n- **In-sample vs causal:** 2008 y 2011 caen en el train inicial → `NaN` OOS (no evaluables con esta ventana, no es que el modelo falle); 2020/2022 sí son OOS y **mantienen cobertura alta también causalmente**. Hallazgo clave: el acierto en crisis grandes y persistentes NO era un artefacto del look-ahead —un HMM reentrenado solo con pasado las sigue capturando—; lo que el look-ahead aportaba era sobre todo la *suavidad* del recorrido histórico, no la detección OOS.\n\n**Veredicto "mejor-para-qué":** D4 es el baseline-puente honesto que separa lo reproducible (detección de crisis grandes) de lo que era fuga de futuro (estabilidad de las etiquetas pasadas), y deja servido el problema —colas y crisis rápidas— que los detectores siguientes deben atacar. Detalle y números finales en `docs/memory/detectors/04_hmm_gaussian_2s.md`.'))

nb = new_notebook(cells=cells, metadata={
    "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
    "language_info": {"name": "python"},
})

ep = ExecutePreprocessor(timeout=2400, kernel_name="python3")
ep.preprocess(nb, {"metadata": {"path": str(ROOT / "notebooks")}})
nbf.write(nb, NB_PATH)

n_err = sum(1 for c in nb.cells for o in c.get("outputs", []) if o.get("output_type") == "error")
print(f"[exec] {NB_PATH.name}: errores={n_err}")
if n_err:
    for c in nb.cells:
        for o in c.get("outputs", []):
            if o.get("output_type") == "error":
                print("  ", o.get("ename"), o.get("evalue"))
